# Generated by Django 4.1.13 on 2023-12-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='valid_t',
            new_name='valid_to',
        ),
    ]
