# Generated by Django 4.1.13 on 2023-12-20 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_rename_valid_t_coupon_valid_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'Купон', 'verbose_name_plural': 'Купоны'},
        ),
    ]
